server:
  port: 7080

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: privateself
    password: 123456
    url: jdbc:oracle:thin:@localhost:1521:orcl


mybatis:
  mapper-locations: classpath:/mapper/**.xml