server:
  port: 7080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${mysqlUserName}
    password: ${mysqlPassword}
    url: jdbc:mysql://${mysqlHost}:3306/privateSelf?serverTimezone=UTC&useSSL=false
  rabbitmq:
    host: locahost
    port: 5672
    username: guest
    password: guest

mybatis:
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mysqlHost: localhost
mysqlUserName: root
mysqlPassword: root