CREATE TABLE PRIVATE_TEST(
    ID NUMBER NOT NULL,
    TESTNAME VARCHAR2(300)  NULL
 );
COMMENT ON TABLE PRIVATE_TEST IS '测试表';
COMMENT ON COLUMN PRIVATE_TEST.ID IS '主键';
COMMENT ON COLUMN PRIVATE_TEST.TESTNAME IS '名称';

ALTER TABLE PRIVATE_TEST ADD CONSTRAINT PK_PRIVATE_TEST PRIMARY KEY (ID);