# 端口号
server:
  port: 7080
# 配置应用程序名称
spring:
  application:
    name: yangsheng-core
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    username: privateself
#    password: 123456
#    url: jdbc:oracle:thin:@localhost:1521:orcl

# eureka配置 客户端配置，注册到服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl